INSERT INTO food(name,imgurl,tag,done) values('Vitória crackers', 'https://static.openfoodfacts.org/images/products/000/000/000/0017/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Cacao', 'https://static.openfoodfacts.org/images/products/000/000/000/0031/front_fr.3.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Sauce Sweety chili 0%', 'https://static.openfoodfacts.org/images/products/000/000/000/0123/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Mini coco', 'https://static.openfoodfacts.org/images/products/000/000/000/0178/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Mendiants', 'https://static.openfoodfacts.org/images/products/000/000/000/0291/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Salade de carottes râpées', 'https://static.openfoodfacts.org/images/products/000/000/000/0949/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Fromage blanc aux myrtilles', 'https://static.openfoodfacts.org/images/products/000/000/000/0970/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Vainilla', 'https://static.openfoodfacts.org/images/products/000/000/000/1007/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Baguette parisien', 'https://static.openfoodfacts.org/images/products/000/000/000/1137/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('&quot;Baguette Lyonnais&quot;', 'https://static.openfoodfacts.org/images/products/000/000/000/1151/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Solène céréales poulet', 'https://static.openfoodfacts.org/images/products/000/000/000/1199/front_fr.13.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Tarte noix de coco', 'https://static.openfoodfacts.org/images/products/000/000/000/1281/front_fr.11.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Salade de fruits exotiques', 'https://static.openfoodfacts.org/images/products/000/000/000/1311/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Chouquettes x 30', 'https://static.openfoodfacts.org/images/products/000/000/000/1328/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Fromage blanc pêche', 'https://static.openfoodfacts.org/images/products/000/000/000/1564/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Crème dessert chocolat', 'https://static.openfoodfacts.org/images/products/000/000/000/1663/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Bouillie de sarrasin', 'https://static.openfoodfacts.org/images/products/000/000/000/1670/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Compote de poire', 'https://static.openfoodfacts.org/images/products/000/000/000/1885/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Paëlla de poulet', 'https://static.openfoodfacts.org/images/products/000/000/000/2042/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Aiguillettes de poulet', 'https://static.openfoodfacts.org/images/products/000/000/000/2103/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Salade shaker chef', 'https://static.openfoodfacts.org/images/products/000/000/000/2219/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Salade de macedoine de légumes', 'https://static.openfoodfacts.org/images/products/000/000/000/2257/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Baguette Poitevin', 'https://static.openfoodfacts.org/images/products/000/000/000/2264/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Suedois thon', 'https://static.openfoodfacts.org/images/products/000/000/000/2363/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Ciabatta Bombay', 'https://static.openfoodfacts.org/images/products/000/000/000/2400/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Ciabatta Roma', 'https://static.openfoodfacts.org/images/products/000/000/000/2417/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Salade tomate', 'https://static.openfoodfacts.org/images/products/000/000/000/3018/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Farine de blé noir', 'https://static.openfoodfacts.org/images/products/000/000/000/3087/front_fr.3.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Mousse chocolat douceur', 'https://static.openfoodfacts.org/images/products/000/000/000/3384/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Brochettes dinde', 'https://static.openfoodfacts.org/images/products/000/000/000/3803/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Suedois saumon', 'https://static.openfoodfacts.org/images/products/000/000/000/3827/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Crêpes au Kamok', 'https://static.openfoodfacts.org/images/products/000/000/000/4299/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Salade shaker taboulé', 'https://static.openfoodfacts.org/images/products/000/000/000/4510/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Sandwich classique fromage', 'https://static.openfoodfacts.org/images/products/000/000/000/4565/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Pain epeautre', 'https://static.openfoodfacts.org/images/products/000/000/000/4572/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Sandiwch Tradition Complet Jambon', 'https://static.openfoodfacts.org/images/products/000/000/000/4732/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Fromage blanc à la creme de marron', 'https://static.openfoodfacts.org/images/products/000/000/000/4794/front_fr.15.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Abondance', 'https://static.openfoodfacts.org/images/products/000/000/000/5005/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Salade verte', 'https://static.openfoodfacts.org/images/products/000/000/000/5081/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('cuisse de poulet direct au four curry', 'https://static.openfoodfacts.org/images/products/000/000/000/5166/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Bagel', 'https://static.openfoodfacts.org/images/products/000/000/000/5241/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Sandwich solene céréales sicilien', 'https://static.openfoodfacts.org/images/products/000/000/000/5272/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Brioché poulet caesar', 'https://static.openfoodfacts.org/images/products/000/000/000/5388/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('BAguette bressan', 'https://static.openfoodfacts.org/images/products/000/000/000/5470/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Baguette Niçois', 'https://static.openfoodfacts.org/images/products/000/000/000/5500/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Pavé de saumon fumé à la ficelle', 'https://static.openfoodfacts.org/images/products/000/000/000/5661/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Torti au saumon fumé', 'https://static.openfoodfacts.org/images/products/000/000/000/7009/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('CORNED BEEF', 'https://static.openfoodfacts.org/images/products/000/000/000/7160/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Salade fusili poulet curry', 'https://static.openfoodfacts.org/images/products/000/000/001/0900/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Pasta box carbonara', 'https://static.openfoodfacts.org/images/products/000/000/001/1631/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Pasta box jambon champignion', 'https://static.openfoodfacts.org/images/products/000/000/001/1686/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Salade Grecque', 'https://static.openfoodfacts.org/images/products/000/000/001/2249/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Tarte chocolat', 'https://static.openfoodfacts.org/images/products/000/000/001/2812/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Salade fraicheur caesar', 'https://static.openfoodfacts.org/images/products/000/000/001/4250/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('salade ibérique', 'https://static.openfoodfacts.org/images/products/000/000/001/4281/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Pâte de fruit fraise', 'https://static.openfoodfacts.org/images/products/000/000/001/4595/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Bretzels en chocolat au lait', 'https://static.openfoodfacts.org/images/products/000/000/001/511/front_fr.3.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Solène céréales deux fromages', 'https://static.openfoodfacts.org/images/products/000/000/001/5172/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('8 Buchettes poulet cœur aux figues', 'https://static.openfoodfacts.org/images/products/000/000/001/5707/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Salade primeur', 'https://static.openfoodfacts.org/images/products/000/000/001/5769/front_fr.4.200.jpg','NONE', false);
INSERT INTO food(name,imgurl,tag,done) values('Mélange fruits secs', 'https://static.openfoodfacts.org/images/products/000/000/001/772/front_fr.3.200.jpg','NONE', false);